### ISSUE TITLE
Can't register plugin -  UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by brandoncollins7** [hapijs/yar#118] opened 2018-03-07 16:10 UTC
Simple code:

```
server = new Hapi.Server()

      await server.register({
        plugin: require('yar'),
        options: {
          storeBlank: false,
          cookieOptions: {
            password: 'the-password-must-be-at-least-32-characters-long',
            isSecure: true
          }
        }
      })
```

Hapi checks: 

```
if (plugin.register.register) {                             // Required plugin
            plugin.register = plugin.register.register;
        }
```

yet plugin.register is undefined. Looks like it should be plugin.plugin.register

**Comment by Marsup** [comment] 2018-03-07 20:08
Duplicate of https://github.com/hapijs/discuss/issues/642, closing.

**Closed by Marsup** 2018-03-07 20:08 UTC
Labels: non-issue
